### ISSUE TITLE
Tensorflow >=2.0 compatibility

### ISSUE THREAD

**Issue by christophM** [microsoft/DiCE#4]
Do you have any plans to make DiCE compatible with tensorflow 2.0 and above?
Would be great to have!

**Comment by raam93** [comment]
Yes, we do have plans to make it TF 2.0 and PyTorch compatible, however, it might take some time. Meanwhile, you are most welcome to contribute - https://github.com/microsoft/DiCE/blob/master/dice_ml/dice.py#L25!

**Comment by raam93** [comment]
Closing this issue as DiCE now supports both TF2 and PyTorch. Please check out https://github.com/microsoft/DiCE/blob/master/notebooks/DiCE_getting_started.ipynb.
