### ISSUE TITLE
Float features wrongly converted to integers in dice_ml.Data

### ISSUE THREAD

**Issue by christophM** [microsoft/DiCE#5]
There is currently a bug that turns all float features into integers.

Problems causing this:

- An extra empty space in ' float' : 
https://github.com/microsoft/DiCE/blob/bab6166530e846456bc913ce3529ab9aa909df5c/dice_ml/data_interfaces/public_data_interface.py#L69
-  Occurrences of `self.continuous_feature_name` in lines 70 to 74 should be replaced with `self.feature` 
https://github.com/microsoft/DiCE/blob/bab6166530e846456bc913ce3529ab9aa909df5c/dice_ml/data_interfaces/public_data_interface.py#L70

A reprex:

```python
import dice_ml
from dice_ml.utils import helpers # helper functions
# Dataset for training an ML model
df = helpers.load_adult_income_dataset()
d = dice_ml.Data(dataframe=df,
                         continuous_features=['age', 'hours_per_week'],
                         outcome_name='income')
print(df.head())
print(d.get_decimal_precisions())

df2 = df.copy()
# Make it float
df2['age'] = df2['age'] + 0.1 

d2 = dice_ml.Data(dataframe=df,
                         continuous_features=['age', 'hours_per_week'],
                         outcome_name='income')

print(df2.head())

print(d.get_decimal_precisions())
```

**Comment by raam93** [comment]
Thanks for pointing out the error, Christoph! I have updated the code.
Also, make sure you feed the modified data 'df2' to dice_ml.Data() to reflect the change.
