### ISSUE TITLE
How to install dice_ml?

### ISSUE THREAD

**Issue by apremgeorge** [microsoft/DiCE#8]
import dice_ml
May i know how to install, is there pip install?

![image](https://user-images.githubusercontent.com/30790120/77613774-a4860e00-6f7f-11ea-9859-84b61c0153c2.png)

**Comment by raam93** [comment]
You can clone or download the latest version of the package from GitHub to your local and run `pip install -e .` from the top-most folder.

Otherwise, the stable version is now available on [PyPI](https://pypi.org/project/dice-ml/). You can simply run `pip install dice-ml` to install.
